language: python

jobs:
  include:
  - python: 2.7
  - python: &latest_py3 3.6

install:
  - pip install deepdiff
  - pip install semver
  - pip install codecov

script:
  - python ./Python/Lib/test.py

after_success:
  codecov
