sudo: false

language: python


jobs:
  include:


    - stage: linting
      os: linux
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env: 
        - BADGE=linux
      install:
        - pip install -r requirements.txt
      script: tox


    - stage: linux
      os: linux
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env: 
        - BADGE=linux
        # revokeAppInstance
        - secure: "GpJtFFiklIEPNmiSKOzFbyhpIouzdFZqHqGgBDGw3JywAyY8gXln11o84Tukpb0EoHMG//fzwB3Ce+uIj42W6sE5y8Iq62yxZB7p78ciGHw7TotVkMi0qc6b+x6mvLNwB7efCAkc+1rdOatWqgx+DWWFhVv9E5wMKzjpG60fAbJa7eK/lDvt63HfKvzUXMXUYvszBRcygaGoqf/5LLLlLZ0Lmi1FYaO+NLV77LojKOw9YYH0KeSZJTWrsn0rYueqRCaQCqN4TRZJafFIC/E85LjfsTfIxUhs/LxY6pWvA9UJAJxJ2Jnm1KswxF3W+LmjFmb0InYbYNHDvf2t05vEiRViqoA820xLzLKNYS2Y2n4k/fVl1KqFoxFuKImRcRzQ4Qh5Gg3Lx9AlmZ5ttOF7jp9t00LZmzf6eR7jK7Y3S5eCWNXIrrw7oJDYRBeSy1+TaolnD0XtKc/TlBc3ehm0ImO4Ue6TSrk/EkOOprP6gxahnLQpRAuBqak5fvo2OGJwUoJX+7Ky8IUhtmq6sln8sqDyZqg5sWenxDr7f6ePJErtbvHH1Zk1L0nJRpTb/etdWhYnUcbKbLhTwfrMHSYIGMkJBfUjdFmziTvtwzpSII1jABAbgwoNtYZoDqWG/CJf8o4SoUTYM0XsBSIxfPR0oIk5kkyZ7s4oVulFkQndzdA="
      install:
        - pip install -r requirements.txt
      script: coverage run ./Lib/typeworld/test.py
      after_success: codecov


    - stage: mac
      os: osx
      language: shell
      osx_image: xcode11.2
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
        - BADGE=osx
        # revokeAppInstance
        - secure: "GpJtFFiklIEPNmiSKOzFbyhpIouzdFZqHqGgBDGw3JywAyY8gXln11o84Tukpb0EoHMG//fzwB3Ce+uIj42W6sE5y8Iq62yxZB7p78ciGHw7TotVkMi0qc6b+x6mvLNwB7efCAkc+1rdOatWqgx+DWWFhVv9E5wMKzjpG60fAbJa7eK/lDvt63HfKvzUXMXUYvszBRcygaGoqf/5LLLlLZ0Lmi1FYaO+NLV77LojKOw9YYH0KeSZJTWrsn0rYueqRCaQCqN4TRZJafFIC/E85LjfsTfIxUhs/LxY6pWvA9UJAJxJ2Jnm1KswxF3W+LmjFmb0InYbYNHDvf2t05vEiRViqoA820xLzLKNYS2Y2n4k/fVl1KqFoxFuKImRcRzQ4Qh5Gg3Lx9AlmZ5ttOF7jp9t00LZmzf6eR7jK7Y3S5eCWNXIrrw7oJDYRBeSy1+TaolnD0XtKc/TlBc3ehm0ImO4Ue6TSrk/EkOOprP6gxahnLQpRAuBqak5fvo2OGJwUoJX+7Ky8IUhtmq6sln8sqDyZqg5sWenxDr7f6ePJErtbvHH1Zk1L0nJRpTb/etdWhYnUcbKbLhTwfrMHSYIGMkJBfUjdFmziTvtwzpSII1jABAbgwoNtYZoDqWG/CJf8o4SoUTYM0XsBSIxfPR0oIk5kkyZ7s4oVulFkQndzdA="
      install:
        - python3 -m pip install --user -r requirements.txt
        - python3 -m pip install --user pyobjc
        - python3 -m pip install --user coverage
      script: python3 -m coverage run ./Lib/typeworld/test.py
      after_success: python3 -m codecov


    - stage: windows
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install --upgrade pytest
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - BADGE=windows
        # revokeAppInstance
        - secure: "GpJtFFiklIEPNmiSKOzFbyhpIouzdFZqHqGgBDGw3JywAyY8gXln11o84Tukpb0EoHMG//fzwB3Ce+uIj42W6sE5y8Iq62yxZB7p78ciGHw7TotVkMi0qc6b+x6mvLNwB7efCAkc+1rdOatWqgx+DWWFhVv9E5wMKzjpG60fAbJa7eK/lDvt63HfKvzUXMXUYvszBRcygaGoqf/5LLLlLZ0Lmi1FYaO+NLV77LojKOw9YYH0KeSZJTWrsn0rYueqRCaQCqN4TRZJafFIC/E85LjfsTfIxUhs/LxY6pWvA9UJAJxJ2Jnm1KswxF3W+LmjFmb0InYbYNHDvf2t05vEiRViqoA820xLzLKNYS2Y2n4k/fVl1KqFoxFuKImRcRzQ4Qh5Gg3Lx9AlmZ5ttOF7jp9t00LZmzf6eR7jK7Y3S5eCWNXIrrw7oJDYRBeSy1+TaolnD0XtKc/TlBc3ehm0ImO4Ue6TSrk/EkOOprP6gxahnLQpRAuBqak5fvo2OGJwUoJX+7Ky8IUhtmq6sln8sqDyZqg5sWenxDr7f6ePJErtbvHH1Zk1L0nJRpTb/etdWhYnUcbKbLhTwfrMHSYIGMkJBfUjdFmziTvtwzpSII1jABAbgwoNtYZoDqWG/CJf8o4SoUTYM0XsBSIxfPR0oIk5kkyZ7s4oVulFkQndzdA="
      python: &latest_py3 3.7
      install:
        - python -m pip install -r requirements.txt
      script: coverage run ./Lib/typeworld/test.py
      after_success: codecov
