sudo: false

language: python


jobs:
  include:
    - stage: linux
      os: linux
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env: 
        - BADGE=linux
        # revokeAppInstance
        - secure: "GpJtFFiklIEPNmiSKOzFbyhpIouzdFZqHqGgBDGw3JywAyY8gXln11o84Tukpb0EoHMG//fzwB3Ce+uIj42W6sE5y8Iq62yxZB7p78ciGHw7TotVkMi0qc6b+x6mvLNwB7efCAkc+1rdOatWqgx+DWWFhVv9E5wMKzjpG60fAbJa7eK/lDvt63HfKvzUXMXUYvszBRcygaGoqf/5LLLlLZ0Lmi1FYaO+NLV77LojKOw9YYH0KeSZJTWrsn0rYueqRCaQCqN4TRZJafFIC/E85LjfsTfIxUhs/LxY6pWvA9UJAJxJ2Jnm1KswxF3W+LmjFmb0InYbYNHDvf2t05vEiRViqoA820xLzLKNYS2Y2n4k/fVl1KqFoxFuKImRcRzQ4Qh5Gg3Lx9AlmZ5ttOF7jp9t00LZmzf6eR7jK7Y3S5eCWNXIrrw7oJDYRBeSy1+TaolnD0XtKc/TlBc3ehm0ImO4Ue6TSrk/EkOOprP6gxahnLQpRAuBqak5fvo2OGJwUoJX+7Ky8IUhtmq6sln8sqDyZqg5sWenxDr7f6ePJErtbvHH1Zk1L0nJRpTb/etdWhYnUcbKbLhTwfrMHSYIGMkJBfUjdFmziTvtwzpSII1jABAbgwoNtYZoDqWG/CJf8o4SoUTYM0XsBSIxfPR0oIk5kkyZ7s4oVulFkQndzdA="
      install:
        - pip install deepdiff
        - pip install semver
        - pip install codecov
        - pip install certifi
        - pip install keyring
        - pip install lxml
        - pip install markdown
        - pip install google-cloud-ndb
        - pip install google-cloud-pubsub

    - stage: mac
      os: osx
      language: sh
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
        - BADGE=osx
        # revokeAppInstance
        - secure: "GpJtFFiklIEPNmiSKOzFbyhpIouzdFZqHqGgBDGw3JywAyY8gXln11o84Tukpb0EoHMG//fzwB3Ce+uIj42W6sE5y8Iq62yxZB7p78ciGHw7TotVkMi0qc6b+x6mvLNwB7efCAkc+1rdOatWqgx+DWWFhVv9E5wMKzjpG60fAbJa7eK/lDvt63HfKvzUXMXUYvszBRcygaGoqf/5LLLlLZ0Lmi1FYaO+NLV77LojKOw9YYH0KeSZJTWrsn0rYueqRCaQCqN4TRZJafFIC/E85LjfsTfIxUhs/LxY6pWvA9UJAJxJ2Jnm1KswxF3W+LmjFmb0InYbYNHDvf2t05vEiRViqoA820xLzLKNYS2Y2n4k/fVl1KqFoxFuKImRcRzQ4Qh5Gg3Lx9AlmZ5ttOF7jp9t00LZmzf6eR7jK7Y3S5eCWNXIrrw7oJDYRBeSy1+TaolnD0XtKc/TlBc3ehm0ImO4Ue6TSrk/EkOOprP6gxahnLQpRAuBqak5fvo2OGJwUoJX+7Ky8IUhtmq6sln8sqDyZqg5sWenxDr7f6ePJErtbvHH1Zk1L0nJRpTb/etdWhYnUcbKbLhTwfrMHSYIGMkJBfUjdFmziTvtwzpSII1jABAbgwoNtYZoDqWG/CJf8o4SoUTYM0XsBSIxfPR0oIk5kkyZ7s4oVulFkQndzdA="
      before_cache:
        # - brew cleanup
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          # - "$HOME/Library/Caches/Homebrew"
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          # update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
      install:
        - pip install deepdiff
        - pip install semver
        - pip install codecov
        - pip install certifi
        - pip install pyobjc
        - pip install keyring
        - pip install lxml
        - pip install markdown
        - pip install google-cloud-ndb
        - pip install google-cloud-pubsub

    - stage: windows
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - BADGE=windows
        # revokeAppInstance
        - secure: "GpJtFFiklIEPNmiSKOzFbyhpIouzdFZqHqGgBDGw3JywAyY8gXln11o84Tukpb0EoHMG//fzwB3Ce+uIj42W6sE5y8Iq62yxZB7p78ciGHw7TotVkMi0qc6b+x6mvLNwB7efCAkc+1rdOatWqgx+DWWFhVv9E5wMKzjpG60fAbJa7eK/lDvt63HfKvzUXMXUYvszBRcygaGoqf/5LLLlLZ0Lmi1FYaO+NLV77LojKOw9YYH0KeSZJTWrsn0rYueqRCaQCqN4TRZJafFIC/E85LjfsTfIxUhs/LxY6pWvA9UJAJxJ2Jnm1KswxF3W+LmjFmb0InYbYNHDvf2t05vEiRViqoA820xLzLKNYS2Y2n4k/fVl1KqFoxFuKImRcRzQ4Qh5Gg3Lx9AlmZ5ttOF7jp9t00LZmzf6eR7jK7Y3S5eCWNXIrrw7oJDYRBeSy1+TaolnD0XtKc/TlBc3ehm0ImO4Ue6TSrk/EkOOprP6gxahnLQpRAuBqak5fvo2OGJwUoJX+7Ky8IUhtmq6sln8sqDyZqg5sWenxDr7f6ePJErtbvHH1Zk1L0nJRpTb/etdWhYnUcbKbLhTwfrMHSYIGMkJBfUjdFmziTvtwzpSII1jABAbgwoNtYZoDqWG/CJf8o4SoUTYM0XsBSIxfPR0oIk5kkyZ7s4oVulFkQndzdA="
      python: &latest_py3 3.7
      install:
        - pip3 install deepdiff
        - pip3 install semver
        - pip3 install codecov
        - pip3 install certifi
        - pip3 install keyring
        - pip3 install lxml
        - pip3 install markdown
        - pip install google-cloud-ndb
        - pip install google-cloud-pubsub



script: coverage run ./Lib/typeWorld/test.py

after_success:
  - codecov
