sudo: false

language: python

os:
  - linux
  - osx

jobs:
  include:
  - stage: osx
    if: os = osx
    python: &latest_py3 3.6
    script: coverage run ./Lib/typeWorld/test.py
  - stage: linux
    if: os = linux
    python: &latest_py3 3.6
    script: coverage run ./Lib/typeWorld/test.py

install:
  - pip install deepdiff
  - pip install semver
  - pip install codecov
  - pip install certifi

after_success:
  - codecov
