sudo: false

language: python

jobs:
  include:
  - python: &latest_py3 3.6

install:
  - pip install deepdiff
  - pip install semver
  - pip install codecov
  - pip install certifi

script:
  - coverage run ./Lib/typeWorld/test.py

after_success:
  - codecov
