sudo: false

language: python

jobs:
  include:
    - stage: linux
      name: "Python 3.7.1 on Xenial Linux"
      os: linux
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - stage: osx
      name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - stage: windows
      name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install deepdiff
  - pip install semver
  - pip install codecov
  - pip install certifi

script: coverage run ./Lib/typeWorld/test.py

after_success:
  - codecov
